version: '3'
services:
  web:
    container_name: wikimd-web
    build: .
    ports:
      - "8089:8089"
    depends_on:
      - mongo
  mongo:
    container_name: wikimd-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/mongodb:/data/db"

volumes:
  mongodb: