Wiki:
  name: World of Warcraft Wiki
  desc: a small wiki about one of the most popular mmorpg games
  icon: /static/logo.png
Server:
  port: 8989
Mongo:
  conn: mongodb://localhost:27017/
  db: wikimd
